---
- name: Install OpenShift
  hosts: localhost
  # Gather facts is required, otherwise this will fail.
  gather_facts: yes
  roles:

  - role: create-agent-iso 
    tags:
    - iso

  - role: install-vsphere
    when: platform == "vsphere"
    tags:
    - vsphere
