---
# https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation/blob/master/roles/vsphere_vm/tasks/static-iso.yml#L89
# https://github.com/sa-ne/openshift4-vmware-upi/blob/514ca0174c840c8ad664d96cefe3f8fbb582d7db/roles/vmware/tasks/vms-cluster-placement.yaml#L6
# This is not idempotent! It fails with error: 
#   "op: reconfig" 
#   "msg: A specified parameter was not correct: spec.cpuAllocation"
- name: Create a virtual machine 
  community.vmware.vmware_guest:
    folder: "{{ vsphere.vm_folder }}"
    cluster: "{{ vsphere.cluster_name }}"
    datacenter: "{{ vsphere.datacenter_name }}"
    name: "{{ cluster_name }}-sno"
    state: poweredon
    guest_id: rhel8_64Guest
    validate_certs: false
    advanced_settings:
    - key: guestinfo.ignition.config.data.encoding
      value: base64
    - key: disk.EnableUUID
      value: 'TRUE'
    - key: stealclock.enable
      value: 'TRUE'
    - key: sched.cpu.latencySensitivity
      value: 'High'
    disk:
    - size_gb: 120
      type: thin
      datastore: WorkloadDatastore
    hardware:
      memory_mb: 20096
      memory_reservation_lock: true
      hotadd_memory: false
      num_cpus: 8
      num_cpu_cores_per_socket: 2
      cpu_reservation: 18400
      hotadd_cpu: false
      hotremove_cpu: false
      scsi: paravirtual
      version: 15
    cdrom:
      - controller_number: 0
        unit_number: 0
        type: iso
        #iso_path: "[{{ datastore_name }}] 43579264-e7e2-4781-4f96-02f3b810c191/{{ agent_iso_name }}"
        iso_path: "[{{ vsphere.datastore_name }}] {{ vsphere.datastore_iso_folder }}/{{ agent_iso_name }}"
        state: present
    networks:
    - name: "{{ vsphere.network_name }}"
      type: static
      start_connected: true
      mac: "{{ vsphere.nic_mac }}"
  register: deploy_vm

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: deploy_vm
