---
# tasks file for create-agent-iso
- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    var: ocp_install_dir
    verbosity: 2

- name: Set fact - OpenShift installation dirs
  ansible.builtin.set_fact:
    ocp_install_assets_dir: "{{ ocp_install_dir }}/ocp_install_{{ ansible_date_time.iso8601 }}"

- name: Set fact - OpenShift installation dirs
  ansible.builtin.set_fact:
    ocp_install_user_manifests_dir: "{{ ocp_install_assets_dir }}/openshift"

- name: Create OpenShift assets dir "{{ ocp_install_assets_dir }}"
  ansible.builtin.file:
    path: "{{ ocp_install_assets_dir }}"
    state: directory

- name: Create OCP user manifests dir "{{ ocp_install_user_manifests_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ ocp_install_user_manifests_dir }}"

- name: Find all butane files
  ansible.builtin.find:
   paths: "{{ role_path }}/files/butane"
  register: butane_files

- name: Generate Machine Config files from Butane files.
  ansible.builtin.shell:                                                                     
    cmd: "/usr/local/bin/butane {{ item.path }} -o {{ ocp_install_user_manifests_dir }}/{{ item.path | basename | splitext | first }}.yaml"
  loop: "{{ butane_files.files }}"                                                                                   


- name: Read ssh and pull secrets
  ansible.builtin.set_fact:
    ssh_key_content: "{{ lookup('ansible.builtin.file', ssh_key_path) }}"
    pull_secret_content: "{{ lookup('ansible.builtin.file', pull_secret_path) }}"

- name: Print the ssh_key content
  ansible.builtin.debug:
    var: ssh_key_content
    verbosity: 2

- name: Print the pull secret content
  ansible.builtin.debug:
    var: pull_secret_content
    verbosity: 3

- name: Generate install-config.yaml
  ansible.builtin.template:
    src: templates/install-config.yaml.j2 
    dest: "{{ ocp_install_assets_dir }}/install-config.yaml"

- name: Generate agent-config.yaml
  ansible.builtin.template:
    src: templates/agent-config.yaml.j2 
    dest: "{{ ocp_install_assets_dir }}/agent-config.yaml"
