---
# tasks file for create-agent-iso

- name: Generate OpenShift manifests
  import_tasks: generate-manifests.yaml
  tags:
  - generate-manifests

- name: Create Agent ISO
  import_tasks: create-iso.yaml
  tags:
  - create-iso

- name: Upload Agent ISO to vSpher
  import_tasks: copy-iso-vsphere.yaml
  when: platform == "vsphere"
  tags:
  - vsphere
  - upload-iso
